from typing import Any

Node = Any

class NVS:
    def commit(*arg) -> Any: ...
    def erase_key(*arg) -> Any: ...
    def get_blob(*arg) -> Any: ...
    def get_i32(*arg) -> Any: ...
    def set_blob(*arg) -> Any: ...
    def set_i32(*arg) -> Any: ...

class Partition:
    def find(*arg) -> Any: ...
    def get_next_update(*arg) -> Any: ...
    def info(*arg) -> Any: ...
    def ioctl(*arg) -> Any: ...
    def mark_app_valid_cancel_rollback(*arg) -> Any: ...
    def readblocks(*arg) -> Any: ...
    def set_boot(*arg) -> Any: ...
    def writeblocks(*arg) -> Any: ...

class RMT:
    def clock_div(*arg) -> Any: ...
    def deinit(*arg) -> Any: ...
    def loop(*arg) -> Any: ...
    def source_freq(*arg) -> Any: ...
    def wait_done(*arg) -> Any: ...
    def write_pulses(*arg) -> Any: ...

class ULP:
    def load_binary(*arg) -> Any: ...
    def run(*arg) -> Any: ...
    def set_wakeup_period(*arg) -> Any: ...

def hall_sensor(*arg) -> Any: ...
def idf_heap_info(*arg) -> Any: ...
def raw_temperature(*arg) -> Any: ...
def wake_on_ext0(*arg) -> Any: ...
def wake_on_ext1(*arg) -> Any: ...
def wake_on_touch(*arg) -> Any: ...